# Change these first
owner: websimww # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Avatars
    url: https://avatars.websim.ai/
    expectedStatusCodes:
      - 200
      - 404
      - 301
  - name: Images
    url: https://images.websim.ai/
    expectedStatusCodes:
      - 200
      - 404
      - 301
  - name: Internal
    url: https://internal.websim.ai/
    expectedStatusCodes:
      - 200
      - 404
      - 301
  - name: OG
    url: https://og.websim.ai/
    expectedStatusCodes:
      - 200
      - 404
      - 301
  - name: Omegabus
    url: https://omegabus.websim.ai/
    expectedStatusCodes:
      - 200
      - 404
      - 301
  - name: Page Images
    url: https://page-images.websim.ai/
    expectedStatusCodes:
      - 200
      - 404
      - 301
  - name: API
    url: https://api.websim.ai/
    expectedStatusCodes:
      - 200
      - 404

status-website:
  baseUrl: /status
  logoUrl: https://styles.redditmedia.com/t5_bdssnd/styles/communityIcon_beaahehzktjd1.png
  favicon: https://styles.redditmedia.com/t5_bdssnd/styles/communityIcon_beaahehzktjd1.png
  themeUrl: https://wwwebsim.glitch.me/upptime.css
  name: Websim Status
  navbar:
    - title: Websim
      href: https://websim.ai/
    - title: Discord
      href: https://discord.gg/aqYTb9sH4Z

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
