# Change these first
owner: websimww # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Avatars
    url: https://avatars.websim.ai/
  - name: Images
    url: https://images.websim.ai/
  - name: Internal
    url: https://internal.websim.ai/
  - name: OG
    url: https://og.websim.ai/
  - name: Omegabus
    url: https://omegabus.websim.ai/
  - name: Page Images
    url: https://page-images.websim.ai/
  - name: API
    url: https://api.websim.ai/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://styles.redditmedia.com/t5_bdssnd/styles/communityIcon_beaahehzktjd1.png
  favicon: https://styles.redditmedia.com/t5_bdssnd/styles/communityIcon_beaahehzktjd1.png
  name: Websim Status
  navbar:
    - title: Websim
      href: https://websim.ai/
    - title: Discord
      href: https://discord.gg/aqYTb9sH4Z

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
